### ISSUE TITLE
Name Validation Feature Flaw

### ISSUE THREAD

**Issue by marclzh** [marclzh/pe#4] opened 2022-11-11 08:24 UTC
![image.png](https://raw.githubusercontent.com/marclzh/pe/main/files/a06a46b3-9fe2-422a-8a93-057af45e5beb.png)

Name field rejects input s/o, which could be an issue with names that have the particular string.

![image.png](https://raw.githubusercontent.com/marclzh/pe/main/files/ca8f2d7c-cbf8-4875-95c8-f76f65296793.png)

As specified by the module website.

**Comment by nus-se-script** [comment] 2022-11-14 20:16
# Team's Response
No details provided by team.

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># Unable to add names containing `-` or `'` characters
>
>![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/af0714c6-5652-429c-951f-fbe000ce958f.png)
>
>
>![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/297435a7-6902-4df8-992c-586d35083fe3.png)
>
>
>![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/ae7bc940-a754-4f25-b921-f8479c168b46.png)
>
>
>It is common for some people's names to include special characters such as `-` and `'`.  Therefore, the user is unable to specify the exact name of the contact.
>
>
>
>
>
>
><hr>
><sub>[original: nus-cs2103-AY2223S1/pe-interim#5569] [original labels: severity.Medium type.FunctionalityBug]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>It is a feature flaw and not a functionality bug because it works as expected, the error message specifies that the name must be alphanumeric.
>
>It is a low severity bug as it only causes minor inconvenience. The user can still add the name, just without the special character. 
>
>This situation will only happen to a user when they first try to add a contact name with a non-alphanumeric character. After the first time, they would know that the name parameter only accepts alphanumeric inputs, hence, they would add names without any special characters and it would not be a recurring issue to the user.
>
>![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/3f542d9b-efd5-4707-a015-fc1536e5b8da.png)
# Items for the Tester to Verify
## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------
## :question: Issue severity

Team chose [`severity.Low`]
Originally [`severity.Medium`]

- [x] I disagree

**Reason for disagreement:** I believe that this flaw should be of severity Medium. Due to the application being targeted at NUS students, which has an extremely diverse population, this would result in a large number of names in NUS having the need for strings such as `s/o` as mentioned in my original bug report, or `-`s as mentioned in the duplicate bug report. This would definitely result in a larger number of occurrences, especially in NUS, and hence I believe that this flaw would be of severity Medium.

-------------------

**Closed as completed** 2023-09-19 12:53 UTC
Labels: severity.Medium, type.FeatureFlaw, status.Done
