### ISSUE TITLE
Duplicate Detection Name Functionality Bug

### ISSUE THREAD

**Issue by marclzh** [marclzh/pe#2] opened 2022-11-11 08:17 UTC
UG specifies that duplicate detection done by name, but does not validate for lowercase/uppercase.
 
![image.png](https://raw.githubusercontent.com/marclzh/pe/main/files/40cb9168-b6e5-4531-8a88-eee809ee032a.png)

![image.png](https://raw.githubusercontent.com/marclzh/pe/main/files/8aaa9ee2-e021-4f74-9563-45eda95fe9a8.png)

Able to add John Doe and John doe with exact same other fields.

- contact add n/John Doe p/98765432 e/johnd@example.com a/John street, block
123, #01-01

- contact add n/John doe p/98765432 e/johnd@example.com a/John street, block
123, #01-01

**Comment by nus-se-script** [comment] 2022-11-14 19:15
# Team's Response
No details provided by team.

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># Duplicate detection for records Functionality Bug
>
>![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/26f81d9b-b498-4000-95a0-5dbd8f1252a9.png)
>
>Duplicate records with names are allowed, as seen in the example above, with no case sensitivity check done.
>
>User might think that it is the same person while it is not.
>
>
>
>
>
><hr>
><sub>[original: nus-cs2103-AY2223S1/pe-interim#2025] [original labels: severity.Medium type.FunctionalityBug]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>Severity is changed to low because duplicated contacts are not expected in regular usage. 
>
>Firstly, your average user is unlikely to have contacts with the same name. This means a large portion of the user base will not be affected by the absence of case-insensitive duplicate detection. This means this bug should only affect a minority of the user base.
>
>Secondly, adding case-insensitive duplicate detection is restrictive in the case where a user does know multiple people with the same name. For example, a user knows 2 'Alex Yeoh's. When adding both to TaskBook, they can add one as 'Alex Yeoh' and another as a different capitalzation, such as 'alex yeoh' or 'alex Yeoh'. Having case-insensitive duplication detection would prevent the users from distinguishing the 2 without adding some other identifier, like a prefiix or different details.
>
>Thirdly, even in the case of an accidental double entry, such as a user adding 'Alex Yeoh', forgetting they added them, then add 'ALex Yeoh' after, it only causes minor inconvenience at worst to correct this mistake. Users can use our `undo` command to undo it, or if from a different session, they can search using `contact find` and easily delete contacts that way. 
>
>Additional accidents after the first accidental repeat addition are far more likely to be malicious in intent to sabotage the application and as such qualify for extreme inputs. Even if a user does add 20 different Alex Yeohs by accident, as mentioned before, they can easily just delete all of them, no harm done. The data is still all there, and the app does not crash or become unusable. Either case is not considered as a bug under module guidelines, so more extreme cases that lead to bigger inconveniences should not be considered.
>
>Additionally, we note that for the case with the aforementioned accidental double(or multiple) entry, it only becomes an issue if they had a typo when adding the same person. It is extremely unlikely that a user would intentionally add the same 'Alex Yeoh' twice but have different capitalizations since most people would add Alex Yeoh twice with proper noun capitalization. The only 2 situations where different capitalizations would happen is in the event of a typo, which should be rare, or deliberate sabotage, which is as mentioned before, not a bug.
>
>For all of the reasons above, this bug only affects a small amount of the user base and is only expected to cause a minor inconvenience. More extreme examples do not qualify as valid instances of this bug under module guidelines. Therefore, this bug is low severity.
>
>Finally, this bug is also not a functionality bug, but a feature flaw instead because we explicitly stated in our UG that names are case-sensitive, therefore, it is working as specified.
>
>![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/ae1b6614-8af2-4032-9107-6b5feccc3f74.png)
# Items for the Tester to Verify
## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------
## :question: Issue type

Team chose [`type.FeatureFlaw`]
Originally [`type.FunctionalityBug`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------
## :question: Issue severity

Team chose [`severity.Low`]
Originally [`severity.Medium`]

- [x] I disagree

**Reason for disagreement:** Although I do agree with the team that this should be under a feature flaw since it is specified by the UG that case-sensitivity is required, I still believe that this bug should be classified as High instead as it is not uncommon to have multiple friends with similar/same name, and I do not think most people will differentiate them based on the case sensitivity of their name, rather having an identifier such as "alex yeoh work" or "alex yeoh school". This bug would then not be particularly rare, and could cause inconvenience to most users.

Furthermore, with the lack of functionality to easily mass delete or transfer the user's data through the GUI, requiring the user to move the tasks for each individual one by one, in the case of accidentally having a duplicate of 1 person, I believe that this flaw in fact affects most users and can cause a major problem for some. In the case of adding duplicate contacts, say 2 alex's which are supposed to be the same person, while adding tasks for the both of them simultaneously, only realising after adding a significant number of tasks, the user would not be able to easily merge the tasks, or even delete a contact due to the lack of available features. I thus think the severity can be upgraded to High instead, in accordance with what was said in the module website about severity.

-------------------

**Closed as completed** 2023-09-19 12:53 UTC
Labels: severity.Medium, type.FunctionalityBug, status.Done
